" ~/.vimrc

" sets , to leader key
let mapleader = ","

" sets how many lines of history vim has to remember
set history=500

" set line numbers
set number

" enable syntax highlighting
syntax on

" enable filetype plugins
filetype plugin on
filetype indent on

" set to auto read when a file is changed from the outside
set autoread

" set 7 lines to the cursor - when moving vertically using j/k
set scrolloff=7

" avoid garbled characters in chinese language windows os
let $LANG='en'
set langmenu=en
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

" turn on the wild menu
set wildmenu
set wildmode=list:longest,full

" ignore compiled files
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

" always show current position
set ruler

" show partial commands in the last line
set showcmd

" show current mode
set showmode

" height of the command bar
set cmdheight=2

" a buffer becomes hidden when it is abandoned
set hidden

" configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" ignore case when searching
set ignorecase

" when searching try to be smart about cases
set smartcase

" makes search act like search in modern browsers
set incsearch

" don't redraw while executing macros
set lazyredraw

" for regular expressions turn magic on
set magic

" show matching brackets when text indicator is over them
"set showmatch

" how many tenths of a second to blink when matching brackets
set matchtime=2

" no annoying sound on errors
set noerrorbells
set visualbell
set t_vb=
set timeoutlen=500

" add a bit extra margin to the left
"set foldcolumn=1

" enable 256 colors palette in gnome terminal
if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif

try
    colorscheme everforest
catch
endtry

set background=dark

" set utf8 as standard encoding and en_us as the standard language
set encoding=utf8

" use unix as the standard file type
set fileformats=unix,dos,mac

" turn backup off, since most stuff is in git anyway
set nobackup
set nowritebackup
set noswapfile

" use spaces instead of tabs
set expandtab

" be smart when using tabs
set smarttab

" tab size == 4 spaces
set shiftwidth=4
set tabstop=4
set softtabstop=4

" linebreak on 500 characters
set linebreak
set textwidth=500

set autoindent " auto indent
set wrap " wrap lines

" return to last edit position when opening files
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" always show the status line
"set laststatus=2

" format the status line
set statusline=\ %F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l\ \ Column:\ %c

" remap vim 0 to first non-blank character
nnoremap 0 ^

" delete trailing white space on save
fun! CleanExtraSpaces()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    silent! %s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfun

if has("autocmd")
    autocmd BufWritePre *.txt,*.js,*.py,*.wiki,*.sh,*.coffee :call CleanExtraSpaces()
endif

" set color of line numbers
highlight LineNr ctermfg=red

" use system clipboard
if has("clipboard")
    if has("macunix")
        set clipboard=unnamed
    else
        set clipboard=unnamedplus
    endif
endif

""" window (splits) management / navigation """

" remap control-w + h/j/k/l to control-h/j/k/l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" remapping turning current window into tab
nnoremap <C-t> <C-w>T

" remapping close all windows in current tab except current window
nnoremap <C-o> <C-w>o

" remapping normalize all window sizes
nnoremap <C-=> <C-w>=

" horizontal splits open below
set splitbelow

" vertical splits open to the right
set splitright

" close current window
nnoremap <leader>c :close<CR>

" open file explore & open file in horizontal split
nnoremap <leader>h :Sexplore<CR>

" open file explore & open file in vertical split on the right
nnoremap <leader>v :Vexplore!<CR>

" open file explore & open file in vertical split on the left
nnoremap <leader>vl :Vexplore<CR>

""" misc mappings """

" toggle paste mode
nnoremap <leader>p :set paste!<CR>

" toggle between spell checking
nnoremap <leader>ss :setlocal spell!<CR>

" disable line numbers
nnoremap <leader>nn :set nonumber<CR>

" enable line numbers
nnoremap <leader>n :set number<CR>

" run a shell
nnoremap <leader>s :shell<CR>

" make
nnoremap <leader>m :make<CR>

" make clean
nnoremap <leader>mc :make clean<CR>

" toggle tab size 2
nnoremap <leader>t2 :set tabstop=2 shiftwidth=2 softtabstop=2<CR>

" toggle tab size 4
nnoremap <leader>t4 :set tabstop=4 shiftwidth=4 softtabstop=4<CR>

" unmap uppercase / lowercase toggling
" can still use ~ built in instead
vnoremap u <Nop>
vnoremap U <Nop>
