#!/usr/bin/zsh

# xclip
alias xclip='xclip -selection c'

# brightness
alias brightset='sudo vim /sys/class/backlight/intel_backlight/brightness'
alias brightmax='echo 535'

#screenshot
alias screenshot='sleep 2; import -window root screenshot.png'
