#!/usr/bin/env python3
# ~/.banner

from random import randint


banner='''

     ▄█    ▄████████ ███▄▄▄▄      ▄██████▄  ███    █▄   ▄█
    ███   ███    ███ ███▀▀▀██▄   ███    ███ ███    ███ ███
    ███   ███    ███ ███   ███   ███    █▀  ███    ███ ███▌
    ███   ███    ███ ███   ███  ▄███        ███    ███ ███▌
    ███ ▀███████████ ███   ███ ▀▀███ ████▄  ███    ███ ███▌
    ███   ███    ███ ███   ███   ███    ███ ███    ███ ███
    ███   ███    ███ ███   ███   ███    ███ ███    ███ ███
█▄ ▄███   ███    █▀   ▀█   █▀    ████████▀  ████████▀  █▀
▀▀▀▀▀▀

'''

qoutes = ['"Do. Or do not. There is no try"\n- Yoda', '“It’s not who I am underneath, but what I do that defines me.”\n- Batman', '“Everything’s impossible until somebody does it.”\n- Batman', '“Our greatest glory is not in ever falling,\nbut in rising every time we fall.”\n– Batman']
qoutes += ['Why do we fall sir? So that we can learn to pick ourselves up."\n- Alfred Pennyworth', '“The night is darkest just before the dawn.\nAnd I promise you. The dawn is coming.”\n- Harvey Dent', '“Sometimes the truth isn’t good enough, sometimes people need more.”\n- Batman', '“A hero can be anyone, even a man doing something as simple\nas reassuring putting a coat on a young boy’s shoulders.”\n- Batman']
qoutes += ['“You do not fear death. You think this makes you strong. It makes you weak.”\nBruce Wayne: "Why?"\n“How can you move faster than possible…fight longer than possible…without\nthe most powerful impulse of the spirit? The fear of death.“']
qoutes += ['"Training is nothing! Will is everything. The will to act."\n- Ra\'s al Ghul', '"What you really fear is inside yourself. You fear your own power.\nYou fear your anger, The drive to do great or terrible things.\nYou must journey inwards" - Ra\'s al Ghul', '"Suffering builds character"\n- Miranda Tate', '"It\'s the job that\'s never started that takes longest to finish"\n- J.R.R. Tolkein']
qoutes += ['“Pay heed to the tales of old wives. It may well be that they\nalone keep in memory what it was once needful for the wise to know."\n- J.R.R. Tolkein', '"All that is gold does not glitter; not all those that wander are lost."\n- J.R.R. Tolkein']
qoutes += ['Frodo: "I wish the Ring had never come to me. I wish none of this had happened."\nGandalf: "So do all who live to see such times, but that is not for them to decide.\nAll we have to decide is what to do with the time that is given to us."']
qoutes += ['“Never tell me the odds.” – Han Solo', '“Fear is the path to the dark side. Fear leads to anger\nanger leads to hate; hate leads to suffering.\nI sense much fear in you.”\n- Yoda', '“Nothing in the world is worth having or worth doing unless\nit means effort, pain, difficulty… I have never in my life\nenvied a human being who led an easy life. I have envied a\ngreat many people who led difficult lives and led them well.”\n- Theodore Roosevelt']
qoutes += ['“Whether You Believe You Can Do a Thing or Not, You Are Right”\n- Henry Ford', '“I must die or be better”\n- Abraham Lincoln', '“Time is the most valuable thing you have; be sure to spend it well.”\n-Lyndon Johnson']
qoutes += ['"A question opens the mind, a statement closes it."\n- Robert Kiyosaki', '"Between stimulus and response there is a space. In that\nspace is our power to choose our response.\nIn our response lies our growth and our freedom."\n-Viktor Frankl']
qoutes += ['"Falure is not falling down, it is not getting up again."\n- Mary Pickford']

print(banner)
print(qoutes[randint(0,len(qoutes)-1)],'\n')
