#!/usr/bin/env python3

#!/usr/bin/python3

#copy this file to ~/.banner

from colorama import Fore, Style

banner='''
 ███████╗███████╗██╗   ██╗███████╗
 ╚══███╔╝██╔════╝██║   ██║██╔════╝
   ███╔╝ █████╗  ██║   ██║███████╗
  ███╔╝  ██╔══╝  ██║   ██║╚════██║
 ███████╗███████╗╚██████╔╝███████║
 ╚══════╝╚══════╝ ╚═════╝ ╚══════╝
'''

print(Fore.YELLOW + Style.DIM + banner + Style.RESET_ALL)
