#!/usr/bin/zsh

rm_crap() {
    rm -rf $HOME/Dropbox/.dropbox.cache/*
}

#move files to trash (cronjob will clean trash periodically)
del() {
  for filename in "$@" ; do
    #check if file exists
    if [ ! -f $filename ] ; then
      if [ ! -d $filename ] ; then
        echo "No such file or directory: $filename"
        continue
      fi
    fi
    
    basefilename=$(basename $filename)
    #check if file in trash w/ same name
    if [[ $(find $HOME/.trash/ -name "$basefilename" | wc -l) = 0 ]] ; then
      newName=$basefilename
    else
      newName=$basefilename.$(date +"%s")
    fi

    #add to trash
    if mv $filename $HOME/.trash/$newName --force ; then
      echo "$filename moved to trash"
    else
      if sudo mv $filename $HOME/.trash/$newName --force ; then
        echo "$filename moved to trash"
      else 
        echo "failed to move $filename to trash"
      fi
    fi
  done 
}
