#!/usr/bin/zsh

# delete unwanted files
rm_crap() {
    rm -rf $HOME/Dropbox/.dropbox.cache/*
}

# override cd so new shells open where we left off
cd() {
    builtin cd $1
    pwd > $HOME/.pwd
}

# move files to trash 
del() {
  for filename in "$@" ; do

    # check if file exists
    if [ ! -f $filename ] ; then
      if [ ! -d $filename ] ; then
        echo "No such file or directory: $filename"
        continue
      fi
    fi
    
    # check if file in trash w/ same name
    basefilename=$(basename $filename)
    if [[ $(find $HOME/.trash/ -name "$basefilename" | wc -l) = 0 ]] ; then
      newName=$basefilename
    else
      newName=$basefilename.$(date +"%s")
    fi

    # add to trash
    errfile="delErr.log"
    if mv $filename $HOME/.trash/$newName --force 2>> $HOME/.trash/$errfile ; then
      echo "$filename moved to trash"
    else
      if sudo mv $filename $HOME/.trash/$newName --force 2>> $HOME/.trash/$errfile ; then
        sudo chown -R $(whoami):$(whoami) $HOME/.trash/$newName
        echo "$filename moved to trash"
      else 
        echo "failed to move $filename to trash"
      fi
    fi
  done 
}

# upload file using sftp
upload() {
  sftp $1 <<< "put $2"
}

# enter first docker container that matches grep
enter() {
  found=$(docker ps | grep $1 | awk {'print $1'} | head -1)
  if [ -z $found ] ; then
    echo "no containers found associated with '$1'"
    return
  fi
  docker exec -it $found sh
}

# run ssha and add keys
ssha() {
  eval `ssh-agent -s`
  ssh-add $HOME/.ssh/id_rsa_git
}
