#!/usr/bin/zsh

#----environment variables----
#system vars
export LANG="C.UTF-8"
export TERMINAL="termite"
export TERM="xterm"
export EDITOR="vim"
export BROWSER="firefox"
export PATH=$HOME/.dots/bin:$PATH
export ZSH_THEME="jangui2" #override in custom_rc

#------aliases------
# xclip
alias xclip='xclip -selection c'

#screenshot
alias screenshot='sleep 2; import -window root screenshot.png'

#lastpass
alias passplz='lpass show -pc'

#venv
alias venv="source ~/.venv/bin/activate"

#print banner text
#baner is unique per system
$HOME/.banner | lolcat


#---unique configs----
source $HOME/.dots/config/zsh/custom_rc #unique to each system
source $HOME/.dots/config/zsh/custom_env_vars #unique to each system
source $HOME/.dots/config/zsh/custom_aliases  #unique to each system
