#!/usr/bin/env python3

#!/usr/bin/python3

from colorama import Fore, Style

zeus='''
 ███████╗███████╗██╗   ██╗███████╗
 ╚══███╔╝██╔════╝██║   ██║██╔════╝
   ███╔╝ █████╗  ██║   ██║███████╗
  ███╔╝  ██╔══╝  ██║   ██║╚════██║
 ███████╗███████╗╚██████╔╝███████║
 ╚══════╝╚══════╝ ╚═════╝ ╚══════╝
'''

print(Fore.YELLOW + Style.DIM + zeus + Style.RESET_ALL)
