#!/usr/bin/zsh
# ~/.zshrc

# functions
source $HOME/.dots/config/zsh/functions

#----environment variables----
# system vars (override in custom_rc)
export LANG="en_US.UTF-8"
export TERMINAL=""
export TERM="xterm"
export EDITOR="vim"
export BROWSER="firefox"
export PATH=$PATH:$HOME/.dots/bin:$HOME/.local/bin
export npm_config_prefix="$HOME/.local"

# zsh theme
if [[ -n $SSH_CONNECTION ]]; then
  export ZSH_THEME="jangui-ssh"
else
  export ZSH_THEME="jangui"
fi

#------aliases------
# git 
alias gitc='git commit -m'
alias gita='git add .'
alias gits='git status'

# xclip
alias xclip='xclip -selection c'

# lastpass
alias passplz='lpass show -pc'

# venv
alias venv="source $HOME/.venv/bin/activate"

# place a Makefile template in current dir
alias maket="cp $HOME/dots/templates/Makefile ."

#-------other--------
# unique system config
source $HOME/.dots/config/zsh/custom_rc

# open shell in last working directory
# .pwd created by custom cd func
if [ -f $HOME/.pwd ]; then
   cd "$(cat $HOME/.pwd)"
fi

# oh-my-zsh config
export ZSH="$HOME/.oh-my-zsh"
plugins=(git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
