#!/usr/bin/zsh
# ~/.zshrc

source "$HOME/.dots/config/zsh/exports"
source "$HOME/.dots/config/zsh/functions"
source "$HOME/.dots/config/zsh/aliases"
source "$HOME/.dots/config/zsh/custom_rc"

if [[ -n "$SSH_CONNECTION" ]]; then
  export ZSH_THEME="jangui-ssh"
else
  export ZSH_THEME="jangui"
fi

if [[ -f "$HOME/.pwd" ]]; then
  cd "$(cat "$HOME/.pwd")"
fi

export ZSH="$HOME/.oh-my-zsh"
plugins=(git zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"
