#!/usr/bin/zsh
# ~/.zshrc

#functions
source $HOME/.dots/config/zsh/functions

#----environment variables----
#system vars (override any in custom_rc)
export LANG="C.UTF-8"
export TERMINAL="termite"
export TERM="xterm"
export EDITOR="vim"
export BROWSER="firefox"
export PATH=$HOME/.dots/bin:$PATH
export ZSH_THEME="jangui2"

#------aliases------
# git commit
alias gitc='git commit -m'

# xclip
alias xclip='xclip -selection c'

#screenshot
alias screenshot='sleep 2; import -window root screenshot.png'

#lastpass
alias passplz='lpass show -pc'

#venv
alias venv="source $HOME/.venv/bin/activate"

#place a Makefile template in current dir
alias maket="cp $HOME/dots/templates/Makefile ."

#---unique configs----
source $HOME/.dots/config/zsh/custom_rc #unique to each system
source $HOME/.dots/config/zsh/custom_env_vars #unique to each system
source $HOME/.dots/config/zsh/custom_aliases  #unique to each system

#-------other--------
#print banner text (unique banner per system)
$HOME/.banner | lolcat

# oh-my-zsh config
export ZSH="/home/jangui/.oh-my-zsh"
plugins=(git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# open shell in last working directory
# cd function must be defined
if [ -f $HOME/.pwd ]; then
   cd "$(cat $HOME/.pwd)"
fi

